### ISSUE TITLE
Cannot find module 'struct-fu/8to16'

### ISSUE THREAD

**Issue by jviotti** [natevw/fatfs#22]
This being conditionally required here: https://github.com/natevw/fatfs/blob/master/dir.js#L271

```js
var workaroundTessel427 = ('\uFFFF'.length !== 1);
...
paddedName = (workaroundTessel427) ? require('struct-fu/8to16').fixString(name) : name
```

However such file doesn't exist in `struct-fu`. Is this functionally no needed anymore?

I don't this this module should breaking encapsulation by requiring an internal file from within a module, since this can change without warning.

**Comment by jviotti** [comment]
Such file was completely removed here: https://github.com/natevw/struct-fu/commit/2db03c4278aa5e587272161de7b4799d88773408, which I guess confirms that the workaround is not needed anymore.

**Comment by natevw** [comment]
What firmware is your Tessel? The thing is, if the workaround is not needed then `workaroundTessel427` should be `false` and the file shouldn't be requested.

I've incorporated your PR (thanks!) and finished cleaning out that old workaround. However, now instead of a "cannot find module" error, you will get a specific assertion if the string handling of your JS platform is not correct. By upgrading your board firmware, you should be able to use fatfs again but please let me know if this is not the case.

**Comment by jviotti** [comment]
@natevw I'm not running this in a Tessel, just on NodeJS in OS X/Linux/Windows.

**Comment by natevw** [comment]
@jviotti Strange. Any idea why `('\uFFFF'.length !== 1)` would be true in your environment, and/or the require getting accessed despite it being false?

**Comment by jviotti** [comment]
@natevw Hm I didn't think of that. I'm actually using http://enclosejs.com so it makes sense that the module blindly parses `require` calls.
